version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    container_name: fov-frontend
  backend:
    build: ./app
    ports:
      - "8000:8000"
    container_name: fov-backend
