version: '3'
services:
  frontend:
    build: 
      context: ./client
      args:
        REACT_APP_API_URL: http://localhost:8000 # TODO: change to https://aviva.fovdashboard.com when on digital ocean
        REACT_APP_WS_URL: ws://localhost:8000/ws
    ports:
      - "3000:3000"
    container_name: fov-frontend
    restart: always
    
  backend:
    build: ./app
    ports:
      - "8000:8000"
    container_name: fov-backend
    restart: always
    volumes:
      - fovdb:/app/db 
      - ./app/aws-iot-certs:/app/aws-iot-certs
    environment:
      - IOT_CLIENT_ID=FOVDashboardClient-Droplet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/status"]
      interval: 1m
      timeout: 10s
      retries: 3